-- Simple user_profiles table without auth dependency
CREATE TABLE IF NOT EXISTS user_profiles (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  gender TEXT NOT NULL,
  country TEXT NOT NULL,
  employment_status TEXT NOT NULL,
  annual_income DECIMAL(15,2) NOT NULL,
  current_savings DECIMAL(15,2) NOT NULL,
  retirement_age_goal INTEGER NOT NULL,
  risk_tolerance TEXT NOT NULL,
  contribution_amount DECIMAL(15,2) NOT NULL,
  contribution_frequency TEXT NOT NULL DEFAULT 'Monthly',
  employer_contribution DECIMAL(15,2) NOT NULL,
  years_contributed INTEGER NOT NULL DEFAULT 0,
  investment_type TEXT NOT NULL DEFAULT 'Balanced',
  fund_name TEXT NOT NULL DEFAULT 'Default Fund',
  marital_status TEXT NOT NULL,
  number_of_dependents INTEGER NOT NULL DEFAULT 0,
  education_level TEXT NOT NULL DEFAULT 'Bachelor',
  health_status TEXT NOT NULL DEFAULT 'Good',
  home_ownership_status TEXT NOT NULL DEFAULT 'Renting',
  investment_experience_level TEXT NOT NULL,
  financial_goals TEXT NOT NULL,
  insurance_coverage TEXT NOT NULL DEFAULT 'Basic',
  pension_type TEXT NOT NULL DEFAULT 'Superannuation',
  withdrawal_strategy TEXT NOT NULL DEFAULT 'Fixed',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert sample data
INSERT INTO user_profiles (
  id, email, name, age, gender, country, employment_status, 
  annual_income, current_savings, retirement_age_goal, risk_tolerance,
  contribution_amount, employer_contribution, marital_status,
  number_of_dependents, investment_experience_level, financial_goals
) VALUES 
(
  'user-001',
  'john.smith@example.com',
  'John Smith',
  35,
  'Male',
  'Australia',
  'Employed',
  85000,
  45000,
  65,
  'Medium',
  1200,
  600,
  'Married',
  2,
  'Intermediate',
  'Retirement planning and children education'
),
(
  'user-002',
  'sarah.johnson@example.com',
  'Sarah Johnson',
  28,
  'Female',
  'Australia',
  'Employed',
  65000,
  18000,
  60,
  'High',
  800,
  400,
  'Single',
  0,
  'Beginner',
  'Early retirement and travel'
),
(
  'user-003',
  'michael.brown@example.com',
  'Michael Brown',
  52,
  'Male',
  'Australia',
  'Self-employed',
  120000,
  180000,
  65,
  'Low',
  2000,
  0,
  'Married',
  1,
  'Expert',
  'Comfortable retirement'
),
(
  'user-004',
  'emma.wilson@example.com',
  'Emma Wilson',
  41,
  'Female',
  'Australia',
  'Employed',
  95000,
  75000,
  62,
  'Medium',
  1500,
  750,
  'Divorced',
  1,
  'Intermediate',
  'Financial independence'
),
(
  'user-005',
  'david.lee@example.com',
  'David Lee',
  29,
  'Male',
  'Australia',
  'Employed',
  72000,
  25000,
  65,
  'High',
  900,
  450,
  'Single',
  0,
  'Beginner',
  'Wealth building and property investment'
) ON CONFLICT (id) DO NOTHING;
